id = "ruby-sorbet"
name = "Ruby Sorbet"
version = "0.0.1"
schema_version = 1
authors = ["Cuong Vuong <cuongvuong.phoenix@gmail.com>"]
description = "Ruby Sorbet LSP for Zed editor"
repository = "https://github.com/cuongvuong-phoenix/zed-ruby-sorbet"

[language_servers.ruby-sorbet]
name = "Ruby Sorbet"
languages = ["Ruby"]

# TODO: Test if we can remove this
[grammars.ruby]
repository = "https://github.com/tree-sitter/tree-sitter-ruby"
commit = "7dbc1e2d0e2d752577655881f73b4573f3fe85d4"
